version: "3"
services:
  client:
    build:
      context: ./client
      args:
        NODE_ENV: development
    volumes:
      - type: bind
        source: ./client
        target: /app
    environment:
      - NODE_ENV=development
    command: npm run start
  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    volumes:
      - type: bind
        source: ./server
        target: /app
    environment:
      - NODE_ENV=development
    command: npm run dev