version: "3"
services:
  client:
    build:
      context: ./client
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start
  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start