GET http://localhost:8000

###

POST http://localhost:4000/api/property HTTP/1.1
content-type: application/json

{
    "type": "Apartment",
    "suburb": "City Centre (Auckland City)",
    "location": "Auckland City , City Centre (Auckland City) , 1010",
    "price": 345,
    "bedrooms": 1,
    "bathrooms": 1,
    "available": "now",
    "images": ["https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI053204_APM53204_0.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI053205_APM53205_2.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI053201_APM53201_3.jpg"]
  }

###

PUT http://localhost:8000/api/property/622d91c1e494841b4ec15021 HTTP/1.1
content-type: application/json

{
    "name": "Spider-Man: No Way Home",
    "time": ["12:00", "14:15", "16:00", "21:30", "23:00"],
    "rating": 8.7
}

###

DELETE http://localhost:8000/api/property/622d93487ac1a1ebe18be155

###
GET http://localhost:4000/api/properties

###
GET http://localhost:8000/api/property/622f08def09fccfc3b297530

###
POST http://localhost:4000/api/seeddata HTTP/1.1
content-type: application/json

[
  {
    "type": "Unit",
    "suburb": "Albany",
    "location": "14 Mulu Place , Albany , 632",
    "price": 560,
    "bedrooms": 2,
    "bathrooms": 2,
    "available": "now",
    "images": ["https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI037353_APM37353_0.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI037350_APM37350_1.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI037352_APM37352_5.jpg"]
  },
  {
    "type": "Unit",
    "suburb": "Newmarket",
    "location": "C516/176 Broadway , Newmarket , 1023",
    "price": 600,
    "bedrooms": 2,
    "bathrooms": 2,
    "available": "2022-4-27",
    "images": ["https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI054956_APM54956_4.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI054949_APM54949_2.jpg", "https://www.aucklandproperty.net/wp-content/uploads/properties/RBPI054953_APM54953_1.jpg"]
  }
]